version: 1.0.{build}

image:
- Visual Studio 2019

configuration:
- Debug
- Release

environment:
  matrix:
  - DBUILD_TESTING: 1
  VCPKG_ROOT: C:\Tools\vcpkg

install:
- cd %VCPKG_ROOT%
- git pull
- .\bootstrap-vcpkg.bat
- .\vcpkg install libusb:x86-windows libusb:x64-windows
- cd %APPVEYOR_BUILD_FOLDER%

before_build:
- cmd: cmake -H. -B./build -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%/scripts/buildsystems/vcpkg.cmake -DBUILD_TESTING=%DBUILD_TESTING%

build:
  verbosity: normal
  project: radio_tool.sln
